import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Fox from "./fox";
import Stoa from "./stoa";
import Weather from "./weather";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log(process.env.NEXT_PUBLIC_ENV_VARIABLE);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Weather />
      <ol class="articles">
        <Fox />
        <Stoa />
        {/* <Link href="/usom">
          <button class="page-button"> USOM</button>
        </Link> */}
      </ol>
    </>
  );
}
